# Generated by Django 2.2.24 on 2021-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Departmentprice',
            fields=[
                # ('id',
                #  models.AutoField(auto_created=True,
                #                   primary_key=True,
                #                   serialize=False,
                #                   verbose_name='ID')),
                ('UniqueCode', models.CharField(max_length=10,
                                                primary_key=True)),
                ('District', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('PriceTime', models.CharField(max_length=30)),
                ('SourceId', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'departmentprice',
            },
        ),
        migrations.CreateModel(
            name='Verifypricemessage',
            fields=[
                # ('id',
                #  models.AutoField(auto_created=True,
                #                   primary_key=True,
                #                   serialize=False,
                #                   verbose_name='ID')),
                ('UniqueID', models.CharField(max_length=10,
                                              primary_key=True)),
                ('District', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('PriceTime', models.CharField(max_length=30)),
                ('SourceId', models.CharField(max_length=10)),
                ('State', models.IntegerField()),
                ('SubmitTime', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'verifypricemessage',
            },
        ),
    ]
