# Generated by Django 2.2.24 on 2021-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                # ('id',
                #  models.AutoField(auto_created=True,
                #                   primary_key=True,
                #                   serialize=False,
                #                   verbose_name='ID')),
                ('UserID', models.CharField(max_length=10, primary_key=True)),
                ('Username', models.CharField(max_length=10)),
                ('District', models.CharField(max_length=30)),
                ('Passwordhash', models.CharField(max_length=100)),
                ('Passwordsalt', models.CharField(max_length=30)),
                ('AdminState', models.IntegerField(default=0)),
                ('Sex', models.IntegerField()),
                ('Telephone', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
